# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:22
from __future__ import unicode_literals

import blog.fields
import blog.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('zip_code', blog.fields.ZipCodeValidatorField(max_length=20, validators=[blog.validators.ZipCodeValidator, blog.validators.ZipCodeValidator, blog.validators.ZipCodeValidator])),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(default=datetime.datetime(2016, 8, 1, 4, 22, 14, 453715, tzinfo=utc), max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
            preserve_default=False,
        ),
    ]
