# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 02:55
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160801_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('gu', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Zip',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(default='', help_text='경도,위도 포맷으로 입력', max_length=50, validators=[blog.validators.lnglat_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Markdown 문법을 써주세요.', validators=[blog.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[blog.validators.MinLengthValidator(4), blog.validators.ZipCodeValidator(True)], verbose_name='제목'),
        ),
    ]
